apiVersion: v1
kind: Service
metadata:
  name: nocap-be
  namespace: nocap
spec:
  type: ClusterIP   # <-- LoadBalancer → ClusterIP 로 변경
  selector:
    app: nocap-be
  ports:
    - name: http
      port: 80
      targetPort: 8080