name: NOCAP-BE CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: chmod +x gradlew
      - run: ./gradlew clean build -x test
      - name: Docker login NCR
        run: |
          echo "${{ secrets.NCR_PASSWORD }}" | docker login ${{ secrets.NCR_REGISTRY }} -u "${{ secrets.NCR_USERNAME }}" --password-stdin
      - name: Build and push
        run: |
          IMAGE=${{ secrets.NCR_REGISTRY }}/${{ secrets.NCR_REPOSITORY }}
          docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
